### ISSUE TITLE
Trakt issue with Fen Light and Umbrella

### ISSUE THREAD

**Issue by afkodi** [Zaxxon709/accountmanager#63]
Thanks for your work on this add-on.

I'm having difficulties getting Fen Light and Umbrella to authorize with Trakt.

Account Viewer shows that it has worked for other addons, but not Fen Light and Umbrella:

![image](https://github.com/user-attachments/assets/724f17ed-7e52-43a4-b102-5e11373950ba)

There doesn't appear to be much in the logs to indicate why, the only thing I can see is:

```
2024-12-17 21:12:48.225 T:10820    info <general>: Account Manager ERROR: Traktit Fen Light Failed!
```

There doesn't appear to be any errors relating to Umbrella.

**Versions:**
Kodi 21.1
accountmgr v2.6.2
fenlight v2.0.06
umbrella v6.7.27

**Comment by Zaxxon709** [comment]
I'm unable to reproduce the error on my end. Both Fen Light and Umbrella authorize without issue and are displayed under View AUthorizations. 

Install the below version of acctview which I have edited to provide more detail in the log and then reproduce the error by opening the View Authorizations for Trakt. Then provide a log and possibly I could narrow down the issue. 

[script.module.acctview_chk.zip](https://github.com/user-attachments/files/18188391/script.module.acctview_chk.zip)

Once you have reproduced the error and have the log you can reinstall the below to eliminate the error notification in Kodi.

[script.module.acctview.zip](https://github.com/user-attachments/files/18188435/script.module.acctview.zip)

**Comment by afkodi** [comment]
I appreciate the quick investigation - I've installed the modified version, see log below:

[kodi_accountmanager.log](https://github.com/user-attachments/files/18189291/kodi_accountmanager.log)

Looks like it could be failing to connect to the Fen Light DB?

Something to point out (and will be visible in the log) is that I use profiles in my Kodi setup - so rather than a path such as `.\Kodi\userdata\addon_data\...`, my profiles have `\Kodi\userdata\profiles\<profilename>\addon_data\...`.  I suspect that may be one of the main differences between our environments.

**Comment by Zaxxon709** [comment]
I can't remember how profiles handle the addon_data. Did you by any chance install these addons in another profile and authorized there? I believe the addon_data is specific to the profile.

Unfortunately, without your setup it's hard for me to troubleshoot what the issue is here. I cannot reproduce this on my end. Maybe I'll test with a profile when I have time.

**Comment by afkodi** [comment]
I've done a bit of digging and the issue is related to profiles as I suspected.

Inside _var.py_, some of the paths being used aren't profile-aware.

I've replaced:
```
addon_data = translatePath('special://userdata/addon_data/')
```

with

```
addon_data = translatePath('special://profile/addon_data/')
```

and also replaced:

```
user_path = os.path.join(home, 'userdata/')
```

with 

```
user_path = translatePath('special://profile/')
```

As per the [wiki](https://kodi.wiki/view/Special_protocol), `special://profile` points to the active profile directory, or `special://masterprofile` if no profile is in use (which in turn points to `special://home/userdata`) - so the above changes should work either with or without profiles.

With those changes above, when I View Authorizations from within my profile, Fen Light and Umbrella report correctly as authorized! Please could you look at incorporating these changes? Any questions let me know. Thanks

**Comment by Zaxxon709** [comment]
Thats great! Thanks for looking into this and testing on your end. I did not consider profiles when I started this. I will look at implementing this in the next update. Cheers

**Comment by afkodi** [comment]
> Thats great! Thanks for looking into this and testing on your end. I did not consider profiles when I started this. I will look at implementing this in the next update. Cheers

Perfect, thanks.

I may have also come across another profile related issue. Once I'd authorized trakt in Account Manager, I tried using the Revoke option and whilst it looked like it had worked, upon loading up Kodi the authorization still appeared to be there.

Looking inside `\userdata\profiles\<profile_name>\addon_data\script.module.accountmgr\settings.xml`, the values for `trakt.token`, `trakt.username`, etc were still there. I tried diagnosing further but I'm not familiar enough with Kodi addon development and/or python so didn't find anything.

**Comment by Zaxxon709** [comment]
> > Thats great! Thanks for looking into this and testing on your end. I did not consider profiles when I started this. I will look at implementing this in the next update. Cheers
> 
> Perfect, thanks.
> 
> I may have also come across another profile related issue. Once I'd authorized trakt in Account Manager, I tried using the Revoke option and whilst it looked like it had worked, upon loading up Kodi the authorization still appeared to be there.
> 
> Looking inside `\userdata\profiles\<profile_name>\addon_data\script.module.accountmgr\settings.xml`, the values for `trakt.token`, `trakt.username`, etc were still there. I tried diagnosing further but I'm not familiar enough with Kodi addon development and/or python so didn't find anything.

I appreciate you taking the time to test. I will have a look when I get a chance. I've been quite busy lately so please be patient.

What I might do is add the fixes for profiles and have you do some testing with your build before I push an update. That's if you're ok doing that?

**Comment by afkodi** [comment]
> > > Thats great! Thanks for looking into this and testing on your end. I did not consider profiles when I started this. I will look at implementing this in the next update. Cheers
> > 
> > 
> > Perfect, thanks.
> > I may have also come across another profile related issue. Once I'd authorized trakt in Account Manager, I tried using the Revoke option and whilst it looked like it had worked, upon loading up Kodi the authorization still appeared to be there.
> > Looking inside `\userdata\profiles\<profile_name>\addon_data\script.module.accountmgr\settings.xml`, the values for `trakt.token`, `trakt.username`, etc were still there. I tried diagnosing further but I'm not familiar enough with Kodi addon development and/or python so didn't find anything.
> 
> I appreciate you taking the time to test. I will have a look when I get a chance. I've been quite busy lately so please be patient.
> 
> What I might do is add the fixes for profiles and have you do some testing with your build before I push an update. That's if you're ok doing that?

Of course, I realise it's a busy time of year. Yes, I can do some testing once the changes are ready.

**Comment by Zaxxon709** [comment]
Happy New Year! 

Could you install the below and test it with your profile setup, please? Let me know how things go. Thanks

[script.module.accountmgr.zip](https://github.com/user-attachments/files/18305203/script.module.accountmgr.zip)
[script.module.acctview.zip](https://github.com/user-attachments/files/18305205/script.module.acctview.zip)

**Comment by Better-Red** [comment]
Hi,

Likewise, Happy New Year, and as ever, thanks for your help.

I tried the mdblist API with Nimbus and it didn’t work unfortunately.  This is on Windows 11 using my fork of OpenWizard, Nimbus 0.1.31 (bumped to 2.1.31 to stop updates breaking anything).  Ivarbrandt has updated his skin to 0.1.32, so let me give this a try later in the day – I must go out.

Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case then prompts FEN Lite to ask for a TMDb API.  Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.  Not a problem for me with my own API’s but maybe my users aren’t so obsessive.

I must get an anonymous email address for GitHub! 😃

Thanks again

**Comment by Better-Red** [comment]
Apologies for the hassle, Nimbus 0.1.32 behaves the same as below (for me). The mdblist API does not sync.

Now I really must go out, I’ll be back in a few hours.

From: Alun Hughes
Sent: 04 January 2025 08:39
To: Zaxxon709/accountmanager ***@***.***>; Zaxxon709/accountmanager ***@***.***>
Subject: RE: [Zaxxon709/accountmanager] Trakt issue with Fen Light and Umbrella (Issue #63)

Hi,

Likewise, Happy New Year, and as ever, thanks for your help.

I tried the mdblist API with Nimbus and it didn’t work unfortunately.  This is on Windows 11 using my fork of OpenWizard, Nimbus 0.1.31 (bumped to 2.1.31 to stop updates breaking anything).  Ivarbrandt has updated his skin to 0.1.32, so let me give this a try later in the day – I must go out.

Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case then prompts FEN Lite to ask for a TMDb API.  Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.  Not a problem for me with my own API’s but maybe my users aren’t so obsessive.

I must get an anonymous email address for GitHub! 😃

Thanks again

**Comment by Zaxxon709** [comment]
> Apologies for the hassle, Nimbus 0.1.32 behaves the same as above (for me). The mdblist API does not sync. Now I really must go out, I’ll be back in a few hours.

I did another edit to acctview to resolve metadata view authorizations not correctly displaying services without keys. Install/update the below.

[script.module.acctview.zip](https://github.com/user-attachments/files/18307387/script.module.acctview.zip)


As for the Nimbus skin, i'm unable to reproduce this on my end. AM syncs the mdblist key just fine. Navigate to the skins settings and if you see ' Invalid Key' displayed then you do not have the correct version of Nimbus Helper installed.

Ensure you have the updated Nimbus helper. Install the below versions and test again. 
Nimbus Skin v0.1.32
Nimbus Helper v0.0.47

Just to note: to sync the mdblist key to either Fentastic or Nimbus you need the skin enabled.

**Comment by Better-Red** [comment]
I don't know what I was doing differently this morning, possibly rushing to get out of the door, but that works great now. Thank you!!!

**Comment by Zaxxon709** [comment]
> Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API. Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.

That's great!

> Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API.  Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.

Could you provide a little more detail on this issue, please? Are you saying AM writes blank fields to the add-ons settings? I'm unable to reproduce this on my end.  I'm unsure where the blank field would be coming from but would like to investigate further to confirm this is not an issue with AM. Could you provide the steps that would produce this error? Thanks

**Comment by Better-Red** [comment]
> > Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API. Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.
> 
> That's great!
> 
> > Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API.  Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.
> 
> Could you provide a little more detail on this issue, please? Are you saying AM writes blank fields to the add-ons settings? I'm unable to reproduce this on my end. I'm unsure where the blank field would be coming from but would like to investigate further to confirm this is not an issue with AM. Could you provide the steps that would produce this error? Thanks

This also seems to have been fixed- maybe by chance. It wasn't me rushing this time!

A simple build: Nimbus, FEN Lite, Chains, The Loop and Account Manager, of course. If the only metadata value in Account Manager is MDblist, and the TMBb field is blank, when syncing Account Manager, TMDb would be cleared from FEN Lite, which would then throw an error. Easily resolved in FEN Lite by restoring the default. I have my own suite of API's and I noticed when configuring a device for one of my daughter's. I solved it for her by populating the Account Manager TMDb field with the FEN Lite default. Following me so far?

My users are just getting their heads around the fact that I've migrated all my builds over to Account Manager and I was anticipating more of the same. Most people will only have Debrid and maybe Trakt credentials.

However, as above, it seems to be solved!

**Comment by Zaxxon709** [comment]
> > > Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API. Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.
> > 
> > 
> > That's great!
> > > Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API.  Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.
> > 
> > 
> > Could you provide a little more detail on this issue, please? Are you saying AM writes blank fields to the add-ons settings? I'm unable to reproduce this on my end. I'm unsure where the blank field would be coming from but would like to investigate further to confirm this is not an issue with AM. Could you provide the steps that would produce this error? Thanks
> 
> This also seems to have been fixed - maybe by chance. It wasn't me rushing this time!
> 
> A simple build: Nimbus, FEN Lite, Chains, The Loop and Account Manager, of course. If the only metadata value in Account Manager is MDblist, and the TMBb field is blank, when syncing Account Manager, TMDb would be cleared from FEN Lite, which would then throw an error. Easily resolved in FEN Lite by restoring the default. I have my own suite of API's and I noticed when configuring a device for one of my daughter's. I solved it for her by populating the Account Manager TMDb field with the FEN Lite default. Following me so far?
> 
> My users are just getting their heads around the fact that I've migrated all my builds over to Account Manager and I was anticipating more of the same. Most people will only have Debrid and maybe Trakt credentials.
> 
> However, as above, it seems to be solved!

ok...sounds good 💯

I will have a finished release in the coming days. Still a few things to complete. I'm awaiting @afkodi to test and report back that profiles are now working so I can put that issue to bed.

**Comment by afkodi** [comment]
> > > > Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API. Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.
> > > 
> > > 
> > > That's great!
> > > > Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API.  Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.
> > > 
> > > 
> > > Could you provide a little more detail on this issue, please? Are you saying AM writes blank fields to the add-ons settings? I'm unable to reproduce this on my end. I'm unsure where the blank field would be coming from but would like to investigate further to confirm this is not an issue with AM. Could you provide the steps that would produce this error? Thanks
> > 
> > 
> > This also seems to have been fixed - maybe by chance. It wasn't me rushing this time!
> > A simple build: Nimbus, FEN Lite, Chains, The Loop and Account Manager, of course. If the only metadata value in Account Manager is MDblist, and the TMBb field is blank, when syncing Account Manager, TMDb would be cleared from FEN Lite, which would then throw an error. Easily resolved in FEN Lite by restoring the default. I have my own suite of API's and I noticed when configuring a device for one of my daughter's. I solved it for her by populating the Account Manager TMDb field with the FEN Lite default. Following me so far?
> > My users are just getting their heads around the fact that I've migrated all my builds over to Account Manager and I was anticipating more of the same. Most people will only have Debrid and maybe Trakt credentials.
> > However, as above, it seems to be solved!
> 
> ok...sounds good 💯
> 
> I will have a finished release in the coming days. Still a few things to complete. I'm awaiting @afkodi to test and report back that profiles are now working so I can put that issue to bed.

Thanks, I'm going to test this as soon as I get chance and report back to you.

**Comment by Zaxxon709** [comment]
> > > > > Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API. Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.
> > > > 
> > > > 
> > > > That's great!
> > > > > Something else I’ve noticed is that Account Manager syncs blank metadata fields, so in my builds case, then prompts FEN Lite to ask for a TMDb API.  Easily sorted at my end by pre-populating the default FEN TMDb API perhaps.
> > > > 
> > > > 
> > > > Could you provide a little more detail on this issue, please? Are you saying AM writes blank fields to the add-ons settings? I'm unable to reproduce this on my end. I'm unsure where the blank field would be coming from but would like to investigate further to confirm this is not an issue with AM. Could you provide the steps that would produce this error? Thanks
> > > 
> > > 
> > > This also seems to have been fixed - maybe by chance. It wasn't me rushing this time!
> > > A simple build: Nimbus, FEN Lite, Chains, The Loop and Account Manager, of course. If the only metadata value in Account Manager is MDblist, and the TMBb field is blank, when syncing Account Manager, TMDb would be cleared from FEN Lite, which would then throw an error. Easily resolved in FEN Lite by restoring the default. I have my own suite of API's and I noticed when configuring a device for one of my daughter's. I solved it for her by populating the Account Manager TMDb field with the FEN Lite default. Following me so far?
> > > My users are just getting their heads around the fact that I've migrated all my builds over to Account Manager and I was anticipating more of the same. Most people will only have Debrid and maybe Trakt credentials.
> > > However, as above, it seems to be solved!
> > 
> > 
> > ok...sounds good 💯
> > I will have a finished release in the coming days. Still a few things to complete. I'm awaiting @afkodi to test and report back that profiles are now working so I can put that issue to bed.
> 
> Thanks, I'm going to test this as soon as I get chance and report back to you.

Ok great...thanks! You can test using the below zips. I've done quite a bit of work on this in the last few weeks. A few new additions and a lot of cleanup and improvements have been made. Any issues, let me know. I will be releasing it in the next day or two.

[script.module.accountmgr.zip](https://github.com/user-attachments/files/18310339/script.module.accountmgr.zip)
[script.module.acctview.zip](https://github.com/user-attachments/files/18310344/script.module.acctview.zip)

**Comment by afkodi** [comment]
Thanks for the improvements - I've done some testing and can confirm that it appears to be working correctly with profiles now!

One issue I have noticed is that when on View Authorizations for Trakt, the menu options to open Umbrella/TMDB Helper/Trakt/AccountManager settings do not work (opening the Fen Light settings does work). The Kodi log contains the following:

> error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'debridit_tk' from 'resources.libs' (C:\Users\afkodi\AppData\Roaming\Kodi\addons\script.module.acctview\resources\libs\__init__.py)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\afkodi\AppData\Roaming\Kodi\addons\script.module.acctview\default.py", line 9, in <module>
                                                       dispatcher.dispatch(_handle, _params)
                                                     File "C:\Users\afkodi\AppData\Roaming\Kodi\addons\script.module.acctview\resources\libs\common\router.py", line 125, in dispatch
                                                       from resources.libs import debridit_tk
                                                   ImportError: cannot import name 'debridit_tk' from 'resources.libs' (C:\Users\afkodi\AppData\Roaming\Kodi\addons\script.module.acctview\resources\libs\__init__.py)
                                                   -->End of Python script error report<--

However, opening the add-on settings when viewing RealDebrid authorizations _does_ work, so it only seems to be viewing Trakt authorizations that is affected.

**Comment by Zaxxon709** [comment]
> Thanks for the improvements - I've done some testing and can confirm that it appears to be working correctly with profiles now!
> 
> One issue I have noticed is that when on View Authorizations for Trakt, the menu options to open Umbrella/TMDB Helper/Trakt/AccountManager settings do not work (opening the Fen Light settings does work). The Kodi log contains the following:
> 
> > error : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
> > - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
> > Error Type: <class 'ImportError'>
> > Error Contents: cannot import name 'debridit_tk' from 'resources.libs' (C:\Users\afkodi\AppData\Roaming\Kodi\addons\script.module.acctview\resources\libs__init__.py)
> > Traceback (most recent call last):
> > File "C:\Users\afkodi\AppData\Roaming\Kodi\addons\script.module.acctview\default.py", line 9, in 
> > dispatcher.dispatch(_handle, _params)
> > File "C:\Users\afkodi\AppData\Roaming\Kodi\addons\script.module.acctview\resources\libs\common\router.py", line 125, in dispatch
> > from resources.libs import debridit_tk
> > ImportError: cannot import name 'debridit_tk' from 'resources.libs' (C:\Users\afkodi\AppData\Roaming\Kodi\addons\script.module.acctview\resources\libs__init__.py)
> > -->End of Python script error report<--
> 
> However, opening the add-on settings when viewing RealDebrid authorizations _does_ work, so it only seems to be viewing Trakt authorizations that is affected.

Thanks for testing! I've fixed the error you reported. I still have some testing to do but should have a release in the coming days.

**Comment by Zaxxon709** [comment]
v2.6.3 released today. Enjoy!

**Comment by afkodi** [comment]
Thanks for all of the effort you've put into fixing this - much appreciated! I'll get it installed soon.
